"""
Minimal valid config used only when futures_analyzer.config.json does not exist.
This is NOT the strategy config — it is a bootstrap fallback only.
All real strategy values must be set in futures_analyzer.config.json.
"""
from __future__ import annotations

MINIMAL_CONFIG: dict = {
    "market_modes": {
        "intraday": {
            "profile_name": "intraday_core",
            "entry_timeframe": "5m",
            "trigger_timeframe": "15m",
            "context_timeframe": "1h",
            "higher_timeframe": "4h",
            "lookback_bars": 600,
        },
        "long_term": {
            "profile_name": "long_term_swing",
            "entry_timeframe": "1h",
            "trigger_timeframe": "4h",
            "context_timeframe": "1d",
            "higher_timeframe": "1w",
            "lookback_bars": 900,
        },
    },
    "market_mode_tuning": {
        "intraday": {
            "target_cap_atr_mult": 2.0,
            "min_confidence": 0.4,
            "max_stop_distance_pct": 2.5,
            "min_evidence_agreement": 3,
            "min_evidence_edge": 1,
            "candidate_quote_asset": "USDT",
            "candidate_min_quote_volume": 25_000_000.0,
            "candidate_pool_limit": 40,
            "candidate_kline_interval": "1h",
            "candidate_kline_lookback": 48,
            "candidate_return_weight": 0.45,
            "candidate_range_weight": 0.40,
            "candidate_consistency_weight": 0.15,
        },
        "long_term": {
            "target_cap_atr_mult": 4.0,
            "min_confidence": 0.45,
            "max_stop_distance_pct": 3.0,
            "min_evidence_agreement": 4,
            "min_evidence_edge": 1,
            "candidate_quote_asset": "USDT",
            "candidate_min_quote_volume": 40_000_000.0,
            "candidate_pool_limit": 30,
            "candidate_kline_interval": "1d",
            "candidate_kline_lookback": 14,
            "candidate_return_weight": 0.55,
            "candidate_range_weight": 0.15,
            "candidate_consistency_weight": 0.30,
        },
    },
    "cache": {
        "market_meta_ttl_seconds": 12.0,
        "realtime_klines_ttl_seconds": 20.0,
        "historical_klines_ttl_seconds": 3600.0,
        "replay_lookback_cap": 96,
    },
    "strategy": {
        "pressure_threshold": 0.05,
        "volume_surge_threshold": 1.05,
        "enable_longs": True,
        "enable_shorts": True,
        "allowed_regimes": ["bearish_trend", "bullish_trend", "range", "breakout", "exhaustion"],
        "signal_transforms": {
            "higher_trend_scale": 10.0,
            "context_trend_scale": 10.0,
            "trigger_momentum_scale": 15.0,
            "entry_momentum_scale": 15.0,
            "buy_pressure_scale": 5.0,
            "funding_momentum_scale": 5.0,
            "macd_histogram_scale": 100.0,
            "vwap_dev_scale": 20.0,
            "volume_surge_cap": 2.0,
            "oi_funding_norm": 0.5,
            "poc_proximity_pct_cap": 2.0,
            "trend_tanh_scale": 100.0,
            "momentum_tanh_scale": 50.0,
        },
        "indicator_params": {
            "ema_fast_period": 20,
            "ema_slow_period": 50,
            "roc_period": 14,
            "volume_window": 20,
            "atr_period": 14,
            "pivot_n": 2,
        },
        "regime_classifier": {
            "adx_trend_threshold": 25.0,
            "adx_weak_threshold": 20.0,
            "atr_volatile_percentile": 85.0,
            "atr_trend_max_percentile": 75.0,
            "adx_slope_exhaustion": -2.0,
            "adx_slope_breakout": 3.0,
            "consensus_weight_higher": 0.50,
            "consensus_weight_context": 0.35,
            "consensus_weight_trigger": 0.15,
            "adx_conf_base": 0.5,
            "adx_conf_range": 0.45,
            "adx_conf_adx_base": 20.0,
            "adx_conf_adx_range": 60.0,
            "di_bias_margin": 1.1,
        },
        "default_signal_weights": {
            "higher_trend": 0.15,
            "context_trend": 0.12,
            "trigger_momentum": 0.10,
            "entry_momentum": 0.08,
            "volume_surge": 0.06,
            "buy_pressure": 0.08,
            "oi_funding_bias": 0.06,
            "funding_momentum": 0.05,
            "structure_position": 0.06,
            "rsi_alignment": 0.05,
            "macd_alignment": 0.05,
            "bb_alignment": 0.04,
            "vwap_alignment": 0.06,
            "market_structure_align": 0.08,
            "cumulative_delta_align": 0.06,
            "volume_poc_proximity": 0.06,
        },
        "regime_gate_thresholds": {
            "trend": 0.4,
            "breakout": 0.3,
            "exhaustion": 0.3,
            "range": 0.3,
            "volatile_chop": 0.5,
            "transition": 0.35,
        },
        "logistic_params": {
            "default": {"steepness": 8.0, "midpoint": 0.5},
        },
        "regime_weights": {
            "default": {
                "higher_trend": 0.15,
                "context_trend": 0.12,
                "trigger_momentum": 0.10,
                "entry_momentum": 0.08,
                "volume_surge": 0.06,
                "buy_pressure": 0.08,
                "oi_funding_bias": 0.06,
                "funding_momentum": 0.05,
                "structure_position": 0.06,
                "rsi_alignment": 0.05,
                "macd_alignment": 0.05,
                "bb_alignment": 0.04,
                "vwap_alignment": 0.06,
                "market_structure_align": 0.08,
                "cumulative_delta_align": 0.06,
                "volume_poc_proximity": 0.06,
            },
        },
        "regime_penalty_multiplier": {"default": 2.0},
        "regime_confidence_ceiling": {"default": 1.0},
        "regime_alignment": {},
        "regime_penalty": {},
        "leverage_caps": {"low": 2, "medium": 4, "high": 6},
        "leverage_floors": {"low": 2, "medium": 2, "high": 3},
        "geometry_quality": {
            "rr_weight": 30.0,
            "rr_cap": 3.0,
            "stop_atr_ideal_min": 0.8,
            "stop_atr_ideal_max": 2.0,
            "stop_atr_bonus": 10.0,
            "stop_atr_penalty": 8.0,
            "anchor_swing_bonus": 12.0,
            "anchor_vwap_bonus": 8.0,
            "anchor_vp_bonus": 6.0,
            "anchor_atr_penalty": 5.0,
            "entry_confluence_bonus": 3.0,
            "target_confluence_bonus": 2.0,
            "base_score": 20.0,
            "min_score": 10.0,
            "max_score": 95.0,
        },
        "long_entry_filters": {
            "enable_enhanced_filters": true,
            "momentum_expansion": {
                "min_momentum_threshold": 0.15,
                "min_volume_surge": 1.3
            },
            "delayed_entry": {
                "min_confirmation_candles": 1,
                "max_confirmation_candles": 3,
                "min_price_continuation_pct": 0.1,
                "min_momentum_sustain": 0.1
            },
            "structure_confirmation": {
                "min_volume_expansion": 1.5,
                "higher_high_buffer_pct": 0.001,
                "min_confirmations_required": 2
            },
            "trend_dominance": {
                "min_ema_separation_pct": 1.5,
                "min_adx_threshold": 25.0,
                "min_di_margin": 5.0
            },
            "pullback_trap": {
                "short_term_momentum_threshold": 0.02,
                "higher_tf_bearish_threshold": -0.01,
                "min_momentum_divergence": 0.03
            },
            "confidence_adjustments": {
                "base_long_penalty": 0.15,
                "weak_trend_penalty": 0.20,
                "momentum_divergence_penalty": 0.15,
                "no_confirmation_penalty": 0.25,
                "bearish_regime_penalty": 0.25,
                "volatile_chop_penalty": 0.20
            }
        },
    },
    "styles": {
        "conservative": {
            "fallback_risk_reward": 1.5,
            "target_cap_atr_mult": 2.0,
            "ambition_penalty_start_atr": 1.5,
            "ambition_penalty_slope": 0.10,
            "min_confidence": 0.45,
            "max_confidence": 1.0,
            "min_quality": 55.0,
            "min_rr_ratio": 1.5,
            "max_stop_distance_pct": 2.0,
            "min_evidence_agreement": 3,
            "min_evidence_edge": 1,
        },
        "aggressive": {
            "fallback_risk_reward": 2.0,
            "target_cap_atr_mult": 3.5,
            "ambition_penalty_start_atr": 2.5,
            "ambition_penalty_slope": 0.06,
            "min_confidence": 0.35,
            "max_confidence": 1.0,
            "min_quality": 45.0,
            "min_rr_ratio": 1.5,
            "max_stop_distance_pct": 3.0,
            "min_evidence_agreement": 3,
            "min_evidence_edge": 1,
        },
    },
    "slippage": {
        "volatility_multipliers": {"low": 0.7, "normal": 1.0, "high": 1.4, "extreme": 2.0},
        "default_model": "moderate",
        "min_viable_rr": 1.0,
    },
    "drawdown": {
        "lookback": 10,
        "mild_threshold_pct": 5.0,
        "moderate_threshold_pct": 15.0,
        "severe_threshold_pct": 30.0,
        "mild_consecutive_losses": 2,
        "moderate_consecutive_losses": 3,
        "severe_consecutive_losses": 5,
    },
    "portfolio": {
        "max_position_pct": 0.20,
        "max_risk_per_trade_pct": 0.02,
        "max_cluster_risk_pct": 0.10,
        "max_total_risk_pct": 0.06,
        "kelly_fraction": 0.25,
        "min_history_for_kelly": 10,
    },
    "find_fallback_top": 3,
}
